version: '2'
services:
  ocsgadmin:
    image: test/ocsg:6.1
    ports:
      - "7001:7001"
    depends_on:
      - mysqldb
    links:
      - mysqldb
  mysqldb:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=welcome1
      - MYSQL_DATABASE=ocsg
      - MYSQL_USER=ocsg
      - MYSQL_PASSWORD=ocsg
